In [1]:
import allel
import zarr
import xarray as xr
import plotly.express as px
import dask.array as da
from collections import Counter
import numpy as np
import json
import hashlib
import numba
import pandas as pd
import bokeh.plotting as bkplt
import bokeh.io as bkio
import bokeh.palettes as bokpalet
import bokeh.models as bkmod
import matplotlib.pyplot as plt
import hmmlearn
from Bio import SeqIO
from pathlib import Path
import malariagen_data

In [2]:
amin1 = malariagen_data.Amin1()#results_cache='~/amin-cache/')
df_samples = amin1.sample_metadata()

In [3]:
df_samples

,sample_id,derived_sample_id,partner_sample_id,contributor,country,location,year,month,latitude,longitude,...,admin1_name,admin1_iso,admin2_name,taxon_y,cohort_admin1_year,cohort_admin1_month,cohort_admin1_quarter,cohort_admin2_year,cohort_admin2_month,cohort_admin2_quarter
0,VBS09378-4248STDY7308980,VBS09378-4248STDY7308980,CB-2-00264,Brandy St. Laurent,Cambodia,Preah Kleang,2016,3,13.667,104.982,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,VBS09382-4248STDY7308981,VBS09382-4248STDY7308981,CB-2-00258,Brandy St. Laurent,Cambodia,Preah Kleang,2016,3,13.667,104.982,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,VBS09397-4248STDY7308982,VBS09397-4248STDY7308982,CB-2-00384,Brandy St. Laurent,Cambodia,Preah Kleang,2016,3,13.667,104.982,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,VBS09460-4248STDY7308986,VBS09460-4248STDY7308986,CB-2-02960,Brandy St. Laurent,Cambodia,Preah Kleang,2016,6,13.667,104.982,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,VBS09466-4248STDY7308989,VBS09466-4248STDY7308989,CB-2-04070,Brandy St. Laurent,Cambodia,Preah Kleang,2016,11,13.667,104.982,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
297,VBS16624-4248STDY7918667,VBS16624-4248STDY7918667,KV-32-01591,Brandy St. Laurent,Cambodia,Sayas,2014,6,13.548,107.025,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
298,VBS16625-4248STDY7918668,VBS16625-4248STDY7918668,KV-32-01499,Brandy St. Laurent,Cambodia,Sayas,2014,6,13.548,107.025,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
299,VBS16626-4248STDY7918669,VBS16626-4248STDY7918669,KV-32-01465,Brandy St. Laurent,Cambodia,Sayas,2014,6,13.548,107.025,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
300,VBS16628-4248STDY7918670,VBS16628-4248STDY7918670,KV-32-01454,Brandy St. Laurent,Cambodia,Sayas,2014,6,13.548,107.025,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
301,VBS16630-4248STDY7918671,VBS16630-4248STDY7918671,KV-31-01949,Brandy St. Laurent,Cambodia,Chamkar San,2014,4,13.595,106.995,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [4]:
# Hashing func
def hash_params(*args, **kwargs):
    """Helper function to hash analysis parameters."""
    o = {
        'args': args,
        'kwargs': kwargs
    }
    s = json.dumps(o, sort_keys=True).encode()
    h = hashlib.md5(s).hexdigest()
    return h

def infer_roh(ind, chrom, analysis_name, results_dir):

    # Construct a key to save the results under
    results_key = hash_params(
        ind=ind,
        chrom=chrom,
        analysis_name=analysis_name
    )

    # Define paths for results files
    data_path = f'{results_dir}/{results_key}-roh.csv'

    try:
        # Try to load previously generated results
        df_roh = pd.read_csv(data_path)
        return df_roh
    except FileNotFoundError:
        # No previous results available, need to run analysis
        print(f'running analysis: {results_key}')


    ds = amin1.snp_calls(region = chrom, sample_query = f'partner_sample_id == "{ind}"')

    gt = ds['call_genotype'].compute()[:,0]
    # Load data

    pos = ds['variant_position'].compute()

    # Infer ROH for ind / chrom
    print(f'computing ROH for {ind}, {chrom}')
    df_roh = allel.roh_mhmm(gv=gt, pos=pos, contig_size = int(np.max(pos)))[0]
    df_roh['ind'] = ind
    df_roh['chrom'] = chrom
    
    
    # Save results to hash cache
    df_roh.to_csv(data_path, index=False)
    print(f'saved results: {results_key}')
    return(df_roh)

In [ ]:
rohlist = []
for sample in df_samples['partner_sample_id'].to_list():
    for contig in amin1.contigs:
        roh = infer_roh(ind=sample, chrom=contig,analysis_name = 'amin1_roh',results_dir='~/amin_cache/roh_v1_analysis/')
        rohlist.append(roh)

running analysis: f2851271a21dae321d6776ee2ead3d13
computing ROH for KV-31-03653, KB663832
saved results: f2851271a21dae321d6776ee2ead3d13
running analysis: 3aef0fa1643cdc6dd56338b40458d98b
computing ROH for KV-31-03653, KB663833
saved results: 3aef0fa1643cdc6dd56338b40458d98b
running analysis: 981dc8936ceae41ba651eea32ed15803
computing ROH for KV-31-03653, KB663844
saved results: 981dc8936ceae41ba651eea32ed15803
running analysis: 514aa7dd3e5f1991a502ba8e98149e0e
computing ROH for KV-31-03653, KB663855
saved results: 514aa7dd3e5f1991a502ba8e98149e0e
running analysis: 1f0e47232841d15438cbc96a5f46e42b
computing ROH for KV-31-03653, KB663866
saved results: 1f0e47232841d15438cbc96a5f46e42b
running analysis: 4c64d8e90f4c43134e5244da55663275
computing ROH for KV-31-03653, KB663877
saved results: 4c64d8e90f4c43134e5244da55663275
running analysis: 1d91fb6124d66b58971ade2c7ec53be7
computing ROH for KV-31-03653, KB663888
saved results: 1d91fb6124d66b58971ade2c7ec53be7
running analysis: d54ca48a4103c48a0408d79445209869
computing ROH for KV-31-03653, KB663899
saved results: d54ca48a4103c48a0408d79445209869
running analysis: e6e4eac7c258e9761229da5bda588ab7
computing ROH for KV-31-03653, KB663910
saved results: e6e4eac7c258e9761229da5bda588ab7
running analysis: 2c090d8eb456b061c0367f4b8bea1b1f
computing ROH for KV-31-03653, KB663921
saved results: 2c090d8eb456b061c0367f4b8bea1b1f
running analysis: 370f51f6688714527c7730bdbb2c6fe1
computing ROH for KV-31-03653, KB663932
saved results: 370f51f6688714527c7730bdbb2c6fe1
running analysis: 8872ca6fc915b737dd6bdc8c1fe78ffd
computing ROH for KV-31-03653, KB663943
saved results: 8872ca6fc915b737dd6bdc8c1fe78ffd
running analysis: fef1d816a0f54b4838f205b1768e6b31
computing ROH for KV-31-03653, KB663955
saved results: fef1d816a0f54b4838f205b1768e6b31
running analysis: b59227fd85d1a845cafbf0ec39005fa2
computing ROH for KV-31-03653, KB664054
saved results: b59227fd85d1a845cafbf0ec39005fa2
running analysis: 8906b24c0fcea4f6fa66e8c759d3b92c
computing ROH for KV-31-03653, KB664165
saved results: 8906b24c0fcea4f6fa66e8c759d3b92c
running analysis: 5c92ad11b5d157518aa778ec64f6b95b
computing ROH for KV-31-03653, KB664255
saved results: 5c92ad11b5d157518aa778ec64f6b95b
running analysis: 83730fcf01019eb0300be508aae7f8c3
computing ROH for KV-31-03653, KB664266
saved results: 83730fcf01019eb0300be508aae7f8c3
running analysis: 517106d194701d576b036e4400d45c75
computing ROH for KV-31-03653, KB664277
saved results: 517106d194701d576b036e4400d45c75
running analysis: fad7ea7624a72339b175be162ad137d1
computing ROH for KV-32-04546, KB663610
saved results: fad7ea7624a72339b175be162ad137d1
running analysis: 7aa96c4bfd86b068064c3b4a12f35ee8
computing ROH for KV-32-04546, KB663611
saved results: 7aa96c4bfd86b068064c3b4a12f35ee8
running analysis: b1c0879d3ee9251a407a10bdf2d00f49
computing ROH for KV-32-04546, KB663622
saved results: b1c0879d3ee9251a407a10bdf2d00f49
running analysis: b5442d642b62b097793ab9e18cb8d284
computing ROH for KV-32-04546, KB663633
saved results: b5442d642b62b097793ab9e18cb8d284
running analysis: 6930f4227d0798063b6ffa38d2b2a366
computing ROH for KV-32-04546, KB663644
saved results: 6930f4227d0798063b6ffa38d2b2a366
running analysis: b3a07470a5038610ed584a37cd83d645
computing ROH for KV-32-04546, KB663655
saved results: b3a07470a5038610ed584a37cd83d645
running analysis: ca734b14c04a20dc3e1a51c868d5a525
computing ROH for KV-32-04546, KB663666
saved results: ca734b14c04a20dc3e1a51c868d5a525
running analysis: bfc23577032dfc8ddbc9b77dd04312b6
computing ROH for KV-32-04546, KB663677
saved results: bfc23577032dfc8ddbc9b77dd04312b6
running analysis: fbb007dc78cc47be89bdaacbb5d8ac52
computing ROH for KV-32-04546, KB663688
saved results: fbb007dc78cc47be89bdaacbb5d8ac52
running analysis: 2d7eb0d1a1741adf070d4975cd10fc29
computing ROH for KV-32-04546, KB663699
saved results: 2d7eb0d1a1741adf070d4975cd10fc29
running analysis: 84faecd2ec4f872283afd5def268d1f5
computing ROH for KV-32-04546, KB663710
saved results: 84faecd2ec4f872283afd5def268d1f5
running analysis: f57d028318b4d088aca369cb7b3a9704
computing ROH for KV-32-04546, KB663721
saved results: f57d028318b4d088aca369cb7b3a9704
running analysis: ca343bb0be3ade3fbcc1a56b6b7f64bd
computing ROH for KV-32-04546, KB663722
saved results: ca343bb0be3ade3fbcc1a56b6b7f64bd
running analysis: 0dd2aac34933ac1ef514a822293d01d9
computing ROH for KV-32-04546, KB663733
saved results: 0dd2aac34933ac1ef514a822293d01d9
running analysis: f5f5eebc12aa7b1f47c80cfd1d2e2007
computing ROH for KV-32-04546, KB663744
saved results: f5f5eebc12aa7b1f47c80cfd1d2e2007
running analysis: 788d7d8b573116e39d1c1a2885309a25
computing ROH for KV-32-04546, KB663755
saved results: 788d7d8b573116e39d1c1a2885309a25
running analysis: c51d1bdb1927b4705579e2f9e27968e3
computing ROH for KV-32-04546, KB663766
saved results: c51d1bdb1927b4705579e2f9e27968e3
running analysis: e22859d42114c0d190320fc9948c442b
computing ROH for KV-32-04546, KB663777
saved results: e22859d42114c0d190320fc9948c442b
running analysis: 9b460bfb313f6b1174f51b867023d286
computing ROH for KV-32-04546, KB663788
saved results: 9b460bfb313f6b1174f51b867023d286
running analysis: 202b83e13570916978d8314fc5ce9529
computing ROH for KV-32-04546, KB663799
saved results: 202b83e13570916978d8314fc5ce9529
running analysis: 1ffd66efb7632ed4457ecf083dfeb7b5
computing ROH for KV-32-04546, KB663810
saved results: 1ffd66efb7632ed4457ecf083dfeb7b5
running analysis: 9e39f653181e84152e96e0953a34e6f6
computing ROH for KV-32-04546, KB663821
saved results: 9e39f653181e84152e96e0953a34e6f6
running analysis: 3ff458d67e99c1bd13d52b67d53a5659
computing ROH for KV-32-04546, KB663832
saved results: 3ff458d67e99c1bd13d52b67d53a5659
running analysis: 3da785f5efbd9568f80b9f8c923b39b8
computing ROH for KV-32-04546, KB663833
saved results: 3da785f5efbd9568f80b9f8c923b39b8
running analysis: 18ffe8827d7e736132118c7a710c5637
computing ROH for KV-32-04546, KB663844
saved results: 18ffe8827d7e736132118c7a710c5637
running analysis: d319d5592072963a3871b69426859af9
computing ROH for KV-32-04546, KB663855
saved results: d319d5592072963a3871b69426859af9
running analysis: f705f28ac9dd6a2a7bf955b2e3fe1018
computing ROH for KV-32-04546, KB663866
saved results: f705f28ac9dd6a2a7bf955b2e3fe1018
running analysis: 7270b56583bc9845661888708985b62a
computing ROH for KV-32-04546, KB663877
saved results: 7270b56583bc9845661888708985b62a
running analysis: ec6eee4f7cf861173c4241351f73dcdf
computing ROH for KV-32-04546, KB663888
saved results: ec6eee4f7cf861173c4241351f73dcdf
running analysis: cf9809ad763d692836aace33621a6575
computing ROH for KV-32-04546, KB663899
saved results: cf9809ad763d692836aace33621a6575
running analysis: 3273b039d2e2dccdcc12271e3d768961
computing ROH for KV-32-04546, KB663910
saved results: 3273b039d2e2dccdcc12271e3d768961
running analysis: 5dd10fc925655957ab3bce896b606d95
computing ROH for KV-32-04546, KB663921
saved results: 5dd10fc925655957ab3bce896b606d95
running analysis: 7b7ee43b646ce479a5ae6d8074091cb4
computing ROH for KV-32-04546, KB663932
saved results: 7b7ee43b646ce479a5ae6d8074091cb4
running analysis: b7a6ddb70105e5568736a75fca41e5a9
computing ROH for KV-32-04546, KB663943
saved results: b7a6ddb70105e5568736a75fca41e5a9
running analysis: ec35b49dfbd6c23cde0413095c39610f
computing ROH for KV-32-04546, KB663955
saved results: ec35b49dfbd6c23cde0413095c39610f
running analysis: 771a1bde99ae988d8ef6cbde799916f1
computing ROH for KV-32-04546, KB664054
saved results: 771a1bde99ae988d8ef6cbde799916f1
running analysis: b317cf38693c70cc188b00f690562bed
computing ROH for KV-32-04546, KB664165
saved results: b317cf38693c70cc188b00f690562bed
running analysis: 8208dcecf403a2d7c6010b86c54701fe
computing ROH for KV-32-04546, KB664255
saved results: 8208dcecf403a2d7c6010b86c54701fe
running analysis: aebe137cb9ae271f96733d26acfa071d
computing ROH for KV-32-04546, KB664266
saved results: aebe137cb9ae271f96733d26acfa071d
running analysis: 6238a604945763049d3e7521290b02fe
computing ROH for KV-32-04546, KB664277
saved results: 6238a604945763049d3e7521290b02fe
running analysis: f6ef16891939b65b29028396d322d115
computing ROH for KV-31-00552, KB663610
saved results: f6ef16891939b65b29028396d322d115
running analysis: fbcfa9ee174ee79ffdd585df648970bb
computing ROH for KV-31-00552, KB663611
saved results: fbcfa9ee174ee79ffdd585df648970bb
running analysis: 4ce5e5f2c3fef30417a644b35b1d0969
computing ROH for KV-31-00552, KB663622
saved results: 4ce5e5f2c3fef30417a644b35b1d0969
running analysis: 7f6ccbda59a164dec5d6ba114404e4d8
computing ROH for KV-31-00552, KB663633
saved results: 7f6ccbda59a164dec5d6ba114404e4d8
running analysis: 487e8271f3330d1980811c88d722d931
computing ROH for KV-31-00552, KB663644
saved results: 487e8271f3330d1980811c88d722d931
running analysis: f7db304e9e081c14e8599b12cc8e7868
computing ROH for KV-31-00552, KB663655
saved results: f7db304e9e081c14e8599b12cc8e7868
running analysis: dabf4ea2d9b1e00f683aa00551f3c630
computing ROH for KV-31-00552, KB663666
saved results: dabf4ea2d9b1e00f683aa00551f3c630
running analysis: 2ae2cd47b680f56f5bf40228832b7004
computing ROH for KV-31-00552, KB663677
saved results: 2ae2cd47b680f56f5bf40228832b7004
running analysis: 81ff9236c7a1a6bc0dc351a9a5e460b5
computing ROH for KV-31-00552, KB663688
saved results: 81ff9236c7a1a6bc0dc351a9a5e460b5
running analysis: afc62f7bf612710e43d04c60faff006a
computing ROH for KV-31-00552, KB663699
saved results: afc62f7bf612710e43d04c60faff006a
running analysis: 2774244a86163b931c699fa3e5b1a7f2
computing ROH for KV-31-00552, KB663710
saved results: 2774244a86163b931c699fa3e5b1a7f2
running analysis: 12207bdd13dc5c9dba1a3a3059a27bd7
computing ROH for KV-31-00552, KB663721
saved results: 12207bdd13dc5c9dba1a3a3059a27bd7
running analysis: 4b25eae15d40633b2f5b088f314b0011
computing ROH for KV-31-00552, KB663722
saved results: 4b25eae15d40633b2f5b088f314b0011
running analysis: 3c75bd543bf392069aa4c2a8cb308561
computing ROH for KV-31-00552, KB663733
saved results: 3c75bd543bf392069aa4c2a8cb308561
running analysis: 5e3d9d9033b83ec7d160f735324915ac
computing ROH for KV-31-00552, KB663744
saved results: 5e3d9d9033b83ec7d160f735324915ac
running analysis: 405ba85b0b8fc51951dc6d581280629a
computing ROH for KV-31-00552, KB663755
saved results: 405ba85b0b8fc51951dc6d581280629a
running analysis: 1989e9c35aacc04b7eadc42f54bae4d1
computing ROH for KV-31-00552, KB663766
saved results: 1989e9c35aacc04b7eadc42f54bae4d1
running analysis: a7f27e934815d55f8e32c09e2e0ff13b
computing ROH for KV-31-00552, KB663777
saved results: a7f27e934815d55f8e32c09e2e0ff13b
running analysis: 88e12540f2b9038c804ca9c8ff8b7efb
computing ROH for KV-31-00552, KB663788
saved results: 88e12540f2b9038c804ca9c8ff8b7efb
running analysis: 7cf0a2e2de3be75ac46fa17fd7b48526
computing ROH for KV-31-00552, KB663799
saved results: 7cf0a2e2de3be75ac46fa17fd7b48526
running analysis: 82cc0383e0b5c5e15be452cbb49f5f2f
computing ROH for KV-31-00552, KB663810
saved results: 82cc0383e0b5c5e15be452cbb49f5f2f
running analysis: 5eb2cd9a17ca942310c2565698f82876
computing ROH for KV-31-00552, KB663821
saved results: 5eb2cd9a17ca942310c2565698f82876
running analysis: ae850e0e829c07a0331b1ff750c227c5
computing ROH for KV-31-00552, KB663832
saved results: ae850e0e829c07a0331b1ff750c227c5
running analysis: fdb3b1d60a2fc0bb7d4c88772ba249b4
computing ROH for KV-31-00552, KB663833
saved results: fdb3b1d60a2fc0bb7d4c88772ba249b4
running analysis: 017c5d6b33d5b7dc1a53333f1b41da7f
computing ROH for KV-31-00552, KB663844
saved results: 017c5d6b33d5b7dc1a53333f1b41da7f
running analysis: 2300f4511b17c69ac6ae27786ed127cf
computing ROH for KV-31-00552, KB663855
saved results: 2300f4511b17c69ac6ae27786ed127cf
running analysis: 4fef2b8b03bfc634a130807f1f0fb664
computing ROH for KV-31-00552, KB663866
saved results: 4fef2b8b03bfc634a130807f1f0fb664
running analysis: d9a1e0b3d0eb7cd44e1702e5b59f195c
computing ROH for KV-31-00552, KB663877
saved results: d9a1e0b3d0eb7cd44e1702e5b59f195c
running analysis: 2787c7683c98ca5bdb198e3cdd64e35f
computing ROH for KV-31-00552, KB663888
saved results: 2787c7683c98ca5bdb198e3cdd64e35f
running analysis: 22a2f5dbca6dfc7f6bccda98e67be737
computing ROH for KV-31-00552, KB663899
saved results: 22a2f5dbca6dfc7f6bccda98e67be737
running analysis: 397ebeb3929cf2d93d54a1fd7cc91542
computing ROH for KV-31-00552, KB663910
saved results: 397ebeb3929cf2d93d54a1fd7cc91542
running analysis: 3cc90353b894d1acb6c4852f6dd5d035
computing ROH for KV-31-00552, KB663921
saved results: 3cc90353b894d1acb6c4852f6dd5d035
running analysis: 95538882c8424e75001e94b15fd60374
computing ROH for KV-31-00552, KB663932
saved results: 95538882c8424e75001e94b15fd60374
running analysis: 9b315cb18965c3e7d7da0e9eb35f1ff1
computing ROH for KV-31-00552, KB663943
saved results: 9b315cb18965c3e7d7da0e9eb35f1ff1
running analysis: 65c18da25515b05195b9fc9ddac561b3
computing ROH for KV-31-00552, KB663955
saved results: 65c18da25515b05195b9fc9ddac561b3
running analysis: 463e7424cd5909e2e875ce6b870f32f6
computing ROH for KV-31-00552, KB664054
saved results: 463e7424cd5909e2e875ce6b870f32f6
running analysis: 27b256b38652cb208d3c880aa2c19ff9
computing ROH for KV-31-00552, KB664165
saved results: 27b256b38652cb208d3c880aa2c19ff9
running analysis: 04a4db1fd787585758cb3549ff40a075
computing ROH for KV-31-00552, KB664255
saved results: 04a4db1fd787585758cb3549ff40a075
running analysis: d15f8adbfa30e14f645cc8eb24e90916
computing ROH for KV-31-00552, KB664266
saved results: d15f8adbfa30e14f645cc8eb24e90916
running analysis: 0222c25d4e488448b6579158cd34415e
computing ROH for KV-31-00552, KB664277
saved results: 0222c25d4e488448b6579158cd34415e
running analysis: 54bbaec60faa13c47c90fd0b232ed344
computing ROH for KV-32-01581, KB663610
saved results: 54bbaec60faa13c47c90fd0b232ed344
running analysis: 37bf9df652407651e2e5cc87a5f024dc
computing ROH for KV-32-01581, KB663611
saved results: 37bf9df652407651e2e5cc87a5f024dc
running analysis: 97fda786e82adb632c32e7ffe4119343
computing ROH for KV-32-01581, KB663622
saved results: 97fda786e82adb632c32e7ffe4119343
running analysis: da250ffd58101742d24223cdbd6f15a8
computing ROH for KV-32-01581, KB663633
saved results: da250ffd58101742d24223cdbd6f15a8
running analysis: fb78db8d158f6e36a9aa3425e59eed6b
computing ROH for KV-32-01581, KB663644
saved results: fb78db8d158f6e36a9aa3425e59eed6b
running analysis: 2e6c8fc8076d4d5e7194ee15c6ef90eb
computing ROH for KV-32-01581, KB663655
saved results: 2e6c8fc8076d4d5e7194ee15c6ef90eb
running analysis: 4daf3401576974ed02ec011da4156f41
computing ROH for KV-32-01581, KB663666
saved results: 4daf3401576974ed02ec011da4156f41
running analysis: 363f0b8b2959a90f764d95aee610a008
computing ROH for KV-32-01581, KB663677
saved results: 363f0b8b2959a90f764d95aee610a008
running analysis: 957fa7871f78a25b1fd9685f324572cb
computing ROH for KV-32-01581, KB663688
saved results: 957fa7871f78a25b1fd9685f324572cb
running analysis: 2986a095fcf76390e15ccc91e47356dc
computing ROH for KV-32-01581, KB663699
saved results: 2986a095fcf76390e15ccc91e47356dc
running analysis: 2899ff5595c3c4de1ae804d1cca23d46
computing ROH for KV-32-01581, KB663710
saved results: 2899ff5595c3c4de1ae804d1cca23d46
running analysis: 3c812cfbe6d8668de12fd3348034f6da
computing ROH for KV-32-01581, KB663721
saved results: 3c812cfbe6d8668de12fd3348034f6da
running analysis: e4ec308e8c71f1efada2692c1405d0cd
computing ROH for KV-32-01581, KB663722
saved results: e4ec308e8c71f1efada2692c1405d0cd
running analysis: 3fd391eaea13431ee08ad5a935ddf28d
computing ROH for KV-32-01581, KB663733
saved results: 3fd391eaea13431ee08ad5a935ddf28d
running analysis: c8f46f7a6179c89b82fa9fb42efd62fc
computing ROH for KV-32-01581, KB663744
saved results: c8f46f7a6179c89b82fa9fb42efd62fc
running analysis: 2670756fe68211a2bbed03ba97d9e01a
computing ROH for KV-32-01581, KB663755
saved results: 2670756fe68211a2bbed03ba97d9e01a
running analysis: 92df2a9579dfa2f013e783a298cae522
computing ROH for KV-32-01581, KB663766
saved results: 92df2a9579dfa2f013e783a298cae522
running analysis: 866b70d81e58a7f2c42f26a50c3d2bea
computing ROH for KV-32-01581, KB663777
saved results: 866b70d81e58a7f2c42f26a50c3d2bea
running analysis: 3a92fefc24eb8c8983151e781f624f76
computing ROH for KV-32-01581, KB663788
saved results: 3a92fefc24eb8c8983151e781f624f76
running analysis: 158d32c59ad080b4325915a1f5c57d7f
computing ROH for KV-32-01581, KB663799
saved results: 158d32c59ad080b4325915a1f5c57d7f
running analysis: 403717fa14b33da4f571ee97489b4d6f
computing ROH for KV-32-01581, KB663810
saved results: 403717fa14b33da4f571ee97489b4d6f
running analysis: bab3df791b9aa0602ded659d90e35736
computing ROH for KV-32-01581, KB663821
saved results: bab3df791b9aa0602ded659d90e35736
running analysis: 8b2242fe09c9ffc0bf2c55340447a064
computing ROH for KV-32-01581, KB663832
saved results: 8b2242fe09c9ffc0bf2c55340447a064
running analysis: ffb4e78218a606647df186d4c2c6b90e
computing ROH for KV-32-01581, KB663833
saved results: ffb4e78218a606647df186d4c2c6b90e
running analysis: 205ae7838027f08b08365f46929ebd95
computing ROH for KV-32-01581, KB663844
saved results: 205ae7838027f08b08365f46929ebd95
running analysis: a8579e8211b14845ad842b2e737c4bb7
computing ROH for KV-32-01581, KB663855
saved results: a8579e8211b14845ad842b2e737c4bb7
running analysis: b6ff1575f274fd5fb49243bdfc8fa015
computing ROH for KV-32-01581, KB663866
saved results: b6ff1575f274fd5fb49243bdfc8fa015
running analysis: a8b639efdcaa0ac2544a8d1cc5fc7aae
computing ROH for KV-32-01581, KB663877
saved results: a8b639efdcaa0ac2544a8d1cc5fc7aae
running analysis: 278960113d623a3b6bb3466a0f6f0ab6
computing ROH for KV-32-01581, KB663888
saved results: 278960113d623a3b6bb3466a0f6f0ab6
running analysis: 4d1f42ead09f0729c1cc4b1d7456f25a
computing ROH for KV-32-01581, KB663899
saved results: 4d1f42ead09f0729c1cc4b1d7456f25a
running analysis: 739a13a5b58b2e488654569db5034843
computing ROH for KV-32-01581, KB663910
saved results: 739a13a5b58b2e488654569db5034843
running analysis: b237ae3000e9a91534f39f24a813bcae
computing ROH for KV-32-01581, KB663921
saved results: b237ae3000e9a91534f39f24a813bcae
running analysis: 4b387eb03b26e86f572510aea2772857
computing ROH for KV-32-01581, KB663932
saved results: 4b387eb03b26e86f572510aea2772857
running analysis: f834964c433d536c0c217c6331a62375
computing ROH for KV-32-01581, KB663943
saved results: f834964c433d536c0c217c6331a62375
running analysis: 3c23a7c389ef8fc7d71eeb357e72af01
computing ROH for KV-32-01581, KB663955
saved results: 3c23a7c389ef8fc7d71eeb357e72af01
running analysis: 4db68c938202742bd52222f1426a15f6
computing ROH for KV-32-01581, KB664054
saved results: 4db68c938202742bd52222f1426a15f6
running analysis: 6b047ac0aaaf7f2773b84e244cbaefc6
computing ROH for KV-32-01581, KB664165
saved results: 6b047ac0aaaf7f2773b84e244cbaefc6
running analysis: 444f5c142e679f306e6a7a3cd0fc2f76
computing ROH for KV-32-01581, KB664255
saved results: 444f5c142e679f306e6a7a3cd0fc2f76
running analysis: 7564d61a2897288138bdde6b6d84f93a
computing ROH for KV-32-01581, KB664266
saved results: 7564d61a2897288138bdde6b6d84f93a
running analysis: a8dd66640a1a10680473119ae5c1c395
computing ROH for KV-32-01581, KB664277
saved results: a8dd66640a1a10680473119ae5c1c395
running analysis: e7772ec35c511d20545f8aa0b09d727a
computing ROH for KV-31-00581, KB663610
saved results: e7772ec35c511d20545f8aa0b09d727a
running analysis: c13c9c4efc28344bdea8efd21f134f54
computing ROH for KV-31-00581, KB663611
saved results: c13c9c4efc28344bdea8efd21f134f54
running analysis: 581f38dd05a191c8771f21f2cd8dd77c
computing ROH for KV-31-00581, KB663622
saved results: 581f38dd05a191c8771f21f2cd8dd77c
running analysis: 66e5b4eb2ac0331db90e6218ebfa86d6
computing ROH for KV-31-00581, KB663633
saved results: 66e5b4eb2ac0331db90e6218ebfa86d6
running analysis: 98592bf1d8ac75b0c8148af69cf60778
computing ROH for KV-31-00581, KB663644
saved results: 98592bf1d8ac75b0c8148af69cf60778
running analysis: c0c765ed81f3df03823b7d50a23f59b4
computing ROH for KV-31-00581, KB663655

In [ ]:
ds = amin1.snp_calls(region = 'KB663610', sample_query = f'partner_sample_id == "CB-2-00264"')

In [ ]:
gt = ds['call_genotype'].compute()[:,0]
# Load data

pos = ds['variant_position'].compute()

In [ ]:
df_roh = allel.roh_mhmm(gv=gt, pos=pos, contig_size = int(np.max(pos)))

In [ ]:
df_roh[0]

        start      stop  length  is_marginal
0           1     51313   51313         True
1       57605     74811   17207        False
2      610810    616846    6037        False
3      864676    871384    6709        False
4      958533    969497   10965        False
..        ...       ...     ...          ...
211  30817899  30863320   45422        False
212  30865346  30943830   78485        False
213  31035226  31041903    6678        False
214  31183042  31188309    5268        False
215  31595928  31606453   10526        False

[216 rows x 4 columns]